[package]
name = "get-my-local-ip"
version = "0.1.0"
authors = ["Travis Johnson <travis@jumprope.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
get_if_addrs = "0.5.3"